### ISSUE TITLE
TypeError: object is not a function

### ISSUE THREAD

**Issue by Danielss89** [primus/primus#3]
Just installed Primus and tried with example server but gets this error:

```
server.js:7
var primus = new Primus(server, { parser: 'JSON' });
                   ^
TypeError: object is not a function
    at Object.<anonymous> (server.js:7:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by devinivy** [comment]
I just got this error.  I expected it to be a little more harsh!  I can just install `ws` and make it right?  Maybe it would be nice if it clarified that a websockets plugin needs to be specified in options.
