### ISSUE TITLE
Primus & isomorphic app

### ISSUE THREAD

**Issue by mirimCZ** [primus/primus#376]
Hi,

I'm using este.js (https://github.com/steida/este - you should check it out, its nice devstack) and I'm having problems with including client side code.

> If you know isomorphic skip this

Este is using React.JS, when you come to some url, template (= made of react components) is first rendered on the server, then sent to client and revived = all other rendering happens on client.

> end of skip

I'm using ES6 with babel. Problem occures when I try to include client code into one of my React components.

Error I'm getting:
```
[piping] can't execute file: e:\projects\best-web-ever\src\server\index.js
[piping] error given was: TypeError: Cannot set property 'Primus' of undefined
    at UMDish (e:/projects/best-web-ever/src/lib/primus-client.js:2:16)
    at Object.<anonymous> (e:/projects/best-web-ever/src/lib/primus-client.js:8:2
)
```

It's from gulp, he takes care of running my server, building, basicly everything I need :) I suppose it happens during rendering my component on server, when react component being rendered tries to import primus client script.

Showing code has no value in my opinion... error occures when I add `import Primus from '../../lib/primus-client'` to beginning of my component. Importing primus from node_modules throws even more insane errors, I don't think that's the way I should go.

I would be glad for any help, there must be something... some article or anything that would solve my problem :)

**Comment by lpinca** [comment]
What is the content of your `primus-client` module?
If you are trying to import the client constructor on the server, you first have to build it:
```js
'use strict';

var Primus = require('primus').createSocket(/* { optional options } */);

//
// Expose the client constructor
//
module.exports = Primus;
```
or if you have access to the `primus` server instance you can simply use `primus.Socket()`.

**Comment by mirimCZ** [comment]
In primus-client.js there is code generated by Primus.save (https://github.com/primus/primus/#client-library).

Maybe I'm missing something... feel free to correct me... but...

When I do `import Primus from 'primus'` - which should be equal to `require('primus')` (is it??). 
> I checked client code, its translated into `__webpack_require__(N)` where N is number for primus module

It doesn't matter if I do import whole `Primus` or only `Primus.createSocket`. I also tried your code, result was same:` I'm getting those insane errors as I spoke about earlier. There is tons of warnings reported to my console, first error is:
```
ERROR in ./~/primus/package.json
Module parse failed: e:\projects\best-web-ever\node_modules\primus\package.json
Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "name": "primus",
|   "version": "3.0.2",
|   "description": "Primus is a simple abstraction around real-time frameworks.
It allows you to easily switch between different frameworks without any code cha
nges.",
 @ ./~/primus/index.js 183:27-52
```

Warnings are also about `Module parse failed: Unexpected token... You may need an appropriate loader...`

**Comment by lpinca** [comment]
The result of `primus.save()` should work fine or well it works if used with node `require`.
I never tried using it with another loader. I'll try to do this later.

**Comment by mirimCZ** [comment]
Thanks man, I appreciate your help :+1: 

If you decide to try it with my app, feel free to ask for explanation, I will try my best, altho I'm no este expert.

I will add example with `primus.save()` in moments.

**Comment by lpinca** [comment]
@mirimCZ this is what i tried in your repo:
```diff
diff --git a/src/client/pages/primuspage.react.js b/src/client/pages/primuspage.react.js
index f185d01..87fbd24 100644
--- a/src/client/pages/primuspage.react.js
+++ b/src/client/pages/primuspage.react.js
@@ -1,8 +1,7 @@
 import Component from '../components/component.react';
 import React from 'react';
 
-//import Primus from 'primus'
-const Primus = require('../../lib/primus-client')
+import Primus from 'primus-client';
 
 export default class PrimusPage extends Component {
   render() {
```
Then I created a `primus-client` folder under `node_modules`. In this folder I added an `index.js` file whose content is the same of https://github.com/mirimCZ/este-primus/blob/master/src/lib/primus-client.js.

Now i get only a warning. I have no idea if this works.

**Comment by mirimCZ** [comment]
Thanks. If it doesn't end up with error it might be ok, but may require some further testing. I'm middle of something right now, will try this tommorow and let you know.

**Comment by lpinca** [comment]
The problem is caused by the fact that when the module is loaded [`this`](https://github.com/mirimCZ/este-primus/blob/master/src/lib/primus-client.js#L8) is `undefined`.

**Comment by lpinca** [comment]
Closing due to inactivity.

**Comment by kkemple** [comment]
In case anyone else runs into this:
https://github.com/kkemple/primus-webpack-plugin
