### ISSUE TITLE
Getting error in your examples

### ISSUE THREAD

**Issue by ilearnio** [primus/primus#400]
Hi, 

I just tried to run your examples "echo" and "authorization", both are giving me error 

```
$ cd examples/authorization
$ npm i
$ node index.js
module.js:338
    throw err;
    ^

Error: Cannot find module 'eventemitter3'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Admin/Code/www/ilearn/tmp/primus/index.js:4:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Tried to install eventemitter3 via npm but it doesn't help. Am I doing something wrong? I was just fallowing instructions...

I'm using Node v4.1.1 and npm 3.3.5.

**Comment by lpinca** [comment]
Try to install the modules on the parent folder.
In your primus folder, run `npm i`, then go in examples/authorization and run `npm i` again.

**Comment by ilearnio** [comment]
Oops, sorry. You are right. Don't know why I did'n tried it... Thanks

**Comment by lpinca** [comment]
No problem.
