### ISSUE TITLE
Connecting Multiple Primus Servers Together

### ISSUE THREAD

**Issue by brownish** [primus/primus#431]
I am trying to set up two servers that are able to emit events and listen to each other's events.

This works on the first server:

```js
var resource = require('primus-resource')
  , Primus = require('primus')
  , http = require('http');

var server = http.createServer();

// Primus server
var primus = new Primus(server, { transformer: 'sockjs', parser: 'JSON' });
  
// Add dependencies and use resource plugin
primus
.use('multiplex', 'primus-multiplex')
.use('emitter', 'primus-emitter')
.use('resource', resource);

function Creature() {}
Creature.prototype.oncommand = function (spark, command, fn) {
  console.log(command);
  fn('Creature just got command: ' + command);
};
Creature.prototype.onwalk = function (spark, fn) {
  // make the creature walk with some code
  console.log('walk');
  fn('Creature started to walk');
};
// Initialize our resource
primus.resource('creature', new Creature());
primus.on('connection', function (spark) {
  console.log('connection');
});
server.listen(process.env.PORT, process.env.IP);

// CLIENT CODE
var Socket = primus.Socket;

var client = new Socket('http://localhost:8080');

// connect to resource
var creature = client.resource('creature');

// wait until resource is ready
creature.on('ready', function () {

  // start calling remote events
  creature.command('sleep', function (res) {
    console.log(res);
  });

  // call the server remote walk event
  creature.walk(function (res) {
    console.log(res);
  });

});

primus.save(__dirname +'/primus.js');
```

I then take the output of `primus.save(__dirname + '/primus.js)` and try this:

```js
var Primus = require('./primus.js');

var Socket = Primus.createSocket({
  transformer: 'sockjs',
  parser: 'JSON',
  plugin: {
    'multiplex': 'primus-multiplex',
    'emitter': 'primus-emitter',
    'resource': require('primus-resource')
  }
});
var client = new Socket('https://xxx.c9users.io');
```
If I take the resulting `primus.js` file and try to require it on another server I am getting this error:

```
TypeError: Cannot set property 'SockJS' of undefined
    at a (/home/ubuntu/workspace/primus.js:2908:111)
    at libraryWrap (/home/ubuntu/workspace/primus.js:2908:117)
    at Object.<anonymous> (/home/ubuntu/workspace/primus.js:7609:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ubuntu/workspace/p.js:1:76)
```

From what I understand from reading through the docs and various issues here, this should work. How can I go about connecting one server to another, and then eventually in the browser as well?

Thanks much!

**Comment by lpinca** [comment]
If you are trying to create a node client you don't need this:
```js
var Primus = require('./primus.js');
```
If your replace that line with
```js
var Primus = require('primus');
```
it should work (assuming that you have installed the required dependencies).

In the browser you have to use the compiled client (the output of `primus.save`).

**Comment by brownish** [comment]
Thanks for the fast reply! I'll try that.

**Comment by lpinca** [comment]
@brownish any update here? Can this be closed?

**Comment by lpinca** [comment]
I close this due to inactivity. Please post back if needed.
