### ISSUE TITLE
Transformer: uws.native is undefined

### ISSUE THREAD

**Issue by sabrehagen** [primus/primus#502]
**Version:**
Primus: 6.0.2
uws: 0.8.0
uws build succeeded.

**Environment:**
  - **Operating system:** Ubuntu 16.04
  - **Node.js:** 7.0.0

**Expected result:**

uws.native is defined

**Actual result:**

uws.native is undefined

```
/app/node_modules/primus/index.js:288
        throw e;
        ^

TypeError: Cannot read property 'server' of undefined
    at child.server (/app/node_modules/primus/transformers/uws/server.js:24:23)
    at child.initialise (/app/node_modules/primus/transformer.js:51:25)
    at child.Transformer (/app/node_modules/primus/transformer.js:24:8)
    at new child (/app/node_modules/extendible/index.js:88:19)
    at Primus.initialise (/app/node_modules/primus/index.js:281:26)
    at new Primus (/app/node_modules/primus/index.js:106:8)
    at Object.<anonymous> (/app/server/app/app.js:19:14)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/server/server.js:5:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
```
**Steps to reproduce:**

```
const Primus = require('primus');
new Primus(app.server, {
    port : 8000,
    transformer : 'uws',
    iknowhttpsisbetter : true
});
```

**Comment by lpinca** [comment]
Sounds like you are using `primus@>=6.0.4` with `uws@<0.10.0`. Those versions are not compatible.

**Comment by sabrehagen** [comment]
Thanks, versions move fast around here.
