### ISSUE TITLE
list argument must be an Array of Buffers

### ISSUE THREAD

**Issue by peacemakr** [primus/primus#520]
**Version:**
6.0.7

**Environment:**
  - **Operating system:**
Mac OSX
  - **Browser:**
Chrome
  - **Node.js:**
5.12.0
**Expected result:**
server should not crash
**Actual result:**
server is crashing with the following message
```
TypeError: list argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:330:13)
    at IncomingMessage.onData (/test5/node_modules/engine.io/lib/transports/polling.js:161:23)
    at emitOne (events.js:90:13)
    at IncomingMessage.emit (events.js:182:7)
    at IncomingMessage.Readable.read (_stream_readable.js:368:10)
    at flow (_stream_readable.js:751:26)
    at resume_ (_stream_readable.js:731:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
**Steps to reproduce:**
Not sure what kind of input is causing that to happen... however this appears to be related to Engine.io not validating inputs etc

**Comment by lpinca** [comment]
I guess either `chunks` or `data` is not a buffer in this [array](https://github.com/socketio/engine.io/blob/e144dc17ad6e3e1d6ce2ab96c6164cd485bf358c/lib/transports/polling.js#L161).

Sounds like an external issue though.

**Comment by peacemakr** [comment]
it works normally in most cases, in fact it only occurred once to me

in any case, the code should be protected

**Comment by lpinca** [comment]
I vaguely remember a similar issue https://github.com/socketio/engine.io/pull/305.

**Comment by lpinca** [comment]
This should have been fixed in `engine.io@3.1.1`. Please reopen if it's not the case.
