### ISSUE TITLE
uws: Cannot read property 'fd' of null

### ISSUE THREAD

**Issue by STRML** [primus/primus#530]
**Version:** 6.0.7

**Environment:**
  - **Operating system:** Linux
  - **Node.js:** 6.9.4

Running Linux; NodeJS via Primus, no SSL.

Stack:

```
/srv/node/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^
TypeError: Cannot read property 'fd' of null
    at child.on (/srv/node/node_modules/primus/transformers/uws/server.js:90:21)
    at child.emit (/srv/node/node_modules/primus/node_modules/eventemitter3/index.js:131:35)
    at emitter (/srv/node/node_modules/emits/index.js:26:22)
    at iterate (/srv/node/node_modules/primus/transformer.js:125:24)
    at done (/srv/node/node_modules/primus/transformer.js:139:7)
    at authorized (/srv/node/node_modules/primus/middleware/authorization.js:22:24)
    at tryCatcher (/srv/node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter (/srv/node/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise.<anonymous> (/srv/node/node_modules/continuation-local-storage/context.js:84:17)
    at bound (domain.js:280:14)
    at Promise.runBound [as _fulfillmentHandler0] (domain.js:293:12)
    at Promise._settlePromise (/srv/node/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/srv/node/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/srv/node/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/srv/node/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/srv/node/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/srv/node/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

This seems to happen at random on a production server; seems to be something like a connection being disconnected before there's a chance to register it - not sure.

The [offending code](https://github.com/primus/primus/blob/7209e8ac472ec23980b8c53ccd8d31c20a243911/transformers/uws/server.js#L90) (appears `socketHandle = soc._handle` is null, not using SSL):

```js
      const ticket = native.transfer(
        socketHandle.fd === -1 ? socketHandle : socketHandle.fd,
        sslState
      );
```

Unfortunately I don't have reproduction steps; we have as of yet been unable to trace down the cause. Any ideas?

**Comment by lpinca** [comment]
No, unfortunately I have no idea. The code has been copied from https://github.com/uWebSockets/uWebSockets/blob/66e964bd0e7222f9a4901f4de2666c3b8a4f8c98/nodejs/dist/uws.js#L476 so maybe it makes sense to open an issue in the uWebSockets repository (I can't do that as I'm blocked).

**Comment by STRML** [comment]
Alright; that helps, I'll start going through the code and see what I can find. I'm not sure if he'll support the wrapper as it's been copy/pasted into another project so I'll give it a whirl first

**Comment by STRML** [comment]
Perhaps related to https://github.com/nodejs/node/pull/5916 in that some sockets may not have handles.

**Comment by STRML** [comment]
Actually I don't believe this has anything to do with `uws` @lpinca. By line 90, we haven't called `native.transfer()` yet, so we're just listening to an `'upgrade'` event and crashing when the second parameter (`soc`) doesn't have a `_handle`.

**Comment by STRML** [comment]
For comparison, ws both listens to socket errors immediately, then checks the `readable` and `writable` props to ensure the socket is still open. I'll make a PR.

**Comment by lpinca** [comment]
Yeah it makes sense, I guess this happens when the socket is destroyed by the client and we are in a middleware for example. I'll try to reproduce in a test case.
