### ISSUE TITLE
TypeError: Cannot read property 'handleUpgrade' of undefined

### ISSUE THREAD

**Issue by peacemakr** [primus/primus#539]
**Version:**
6.0.8

**Environment:**
  - Mac OS X
  - Chrome
  - 5.12.0

**Expected result:**
Work without issues

**Actual result:**
Getting error
TypeError: Cannot read property 'handleUpgrade' of undefined
```
4|APP      | TypeError: Cannot read property 'handleUpgrade' of undefined
4|APP      |     at /test/node_modules/engine.io/lib/server.js:360:12
4|APP      |     at Server.verify (/test/node_modules/engine.io/lib/server.js:171:3)
4|APP      |     at Server.handleUpgrade (/test/node_modules/engine.io/lib/server.js:349:8)
4|APP      |     at child.<anonymous> (/test/node_modules/primus/transformers/engine.io/server.js:49:18)
4|APP      |     at child.emit (/test/node_modules/primus/node_modules/eventemitter3/index.js:131:35)
4|APP      |     at emitter (/test/node_modules/emits/index.js:26:22)
4|APP      |     at iterate (/test/node_modules/primus/transformer.js:125:24)
4|APP      |     at iterate (/test/node_modules/primus/transformer.js:126:60)
4|APP      |     at done (/test/node_modules/primus/transformer.js:139:7)
4|APP      |     at authorized (/test/node_modules/primus/middleware/authorization.js:22:24)
```
**Steps to reproduce:**
I upgraded the following today
Package               Current  Wanted    Latest  Location
engine.io               1.8.2   1.8.2     2.0.0  application-name
engine.io-client        1.8.2   1.8.2     2.0.0  application-name

**Comment by lpinca** [comment]
See https://github.com/socketio/engine.io/issues/473.

**Comment by lpinca** [comment]
It should work now if you use `primus@6.0.9`.
