### ISSUE TITLE
Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by 0fork** [primus/primus#597]
**Version:** 7.0.0

**Environment:**
  - **Operating system:** Ubuntu 16.04
  - **Browser:** Chrome
  - **Node.js:** 7.10

**Expected result:**
Successful wss connection.

**Actual result:**
When I try to connect from browser to the server, I get this error:
```
TypeError: Cannot read property 'headers' of undefined
    at service.handleUpgrade (/src/node_modules/primus/transformers/websockets/server.js:37:28)
    at WebSocketServer.completeUpgrade (/src/node_modules/ws/lib/WebSocketServer.js:270:5)
    at WebSocketServer.handleUpgrade (/src/node_modules/ws/lib/WebSocketServer.js:197:10)
    at child.on (/src/node_modules/primus/transformers/websockets/server.js:35:18)
    at child.emit (/src/node_modules/eventemitter3/index.js:131:35)
    at emitter (/src/node_modules/emits/index.js:26:22)
    at iterate (/src/node_modules/primus/transformer.js:125:24)
    at done (/src/node_modules/primus/transformer.js:139:7)
    at Primus.client (/src/node_modules/primus/middleware/authorization.js:19:49)
    at iterate (/src/node_modules/primus/transformer.js:136:14)
    at iterate (/src/node_modules/primus/transformer.js:126:60)
    at iterate (/src/node_modules/primus/transformer.js:126:60)
    at iterate (/src/node_modules/primus/transformer.js:126:60)
    at iterate (/src/node_modules/primus/transformer.js:126:60)
    at iterate (/src/node_modules/primus/transformer.js:126:60)
    at iterate (/src/node_modules/primus/transformer.js:132:14)
    at child.forEach (/src/node_modules/primus/transformer.js:141:4)
    at child.upgrade (/src/node_modules/primus/transformer.js:202:8)
    at emitThree (events.js:116:13)
    at Server.emit (events.js:197:7)
    at onParserExecuteCommon (_http_server.js:460:14)
    at onParserExecute (_http_server.js:419:3)
```
As you can see I'm using ws as a transformer and I'm not sure whether this is a ws bug or primus bug. The error comes from primus but could be that ws' completeUpgrade doesn't do something right.

Server code looks like this:
```
// credentials is cert keys and server is express server
let https_server = https.createServer(credentials, server)

const primus_server = new Primus(https_server, { 
    pathname: '/ws', 
    compression: true, 
    transformer: 'websockets'
})
```

Interesting thing is that everything works perfectly if I put nginx as a reverse proxy between browser and server. This error comes up only if I connect straight to server's port. My gut feeling is that this has got something to do with upgrade and SSL but unfortunately I don't know websockets well enough to debug further.

**Comment by lpinca** [comment]
I think you are using `ws@3.0.0` with `primus@7.0.0`.
Try to update primus to version 7.0.2, it should fix the issue.

**Comment by 0fork** [comment]
@lpinca Huge thanks! Works like magic now.
