### ISSUE TITLE
TypeError on closed server

### ISSUE THREAD

**Issue by renedx** [primus/primus#612]
**Version:** ^7.1.0

**Environment:**
  - **Operating system:** CentOS
  - **Browser:** N/A
  - **Node.js:** 8.4.0

**Expected result:**
Should close all connections nicely

**Actual result:**
Crashes
```
TypeError: Cannot read property 'call' of null
    at Sparky.message (/loc/node_modules/primus/spark.js:198:19)
    at emitOne (events.js:115:13)
    at Sparky.emit (events.js:210:7)
    at WebSocket.emitter (/loc/node_modules/emits/index.js:26:22)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (/loc/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/loc/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/loc/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/loc/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/loc/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/loc/node_modules/ws/lib/WebSocket.js:139:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
```

**Steps to reproduce:**
On a server with open connections thats talking active with clients (using WS), call server.close();
It does close all connections, but some events that are still processing are crashing the node process fully.

We use server.close to gracefully shutdown nodes in emergency, debugging or upgrading. So the node processes can still handle background tasks but do not handle any incoming traffic.

**Comment by lpinca** [comment]
What is `server`? A `Primus` server or a plain HTTP server?

**Comment by renedx** [comment]
Using primus.createServer :)

```js
  static bind () {
    this.server = primus.createServer({
      'port': config.websocket || 8001,
      'transformer': 'websockets'
    });

    this.server.on('connection', (spark) => {
      return new Websocket(spark);
    });

    process.on('SIGTERM', () => {
      log.info('Grace close WS');
      this.server.close();
    });
  }
```

**Comment by lpinca** [comment]
Ok ok, `Primus#close()` is a private method and it doesn't close the open connections.
You may want to use `Primus#destroy()` or the alias `Primus#end()`.

**Comment by renedx** [comment]
Oh wow, how did I end up using that :)
Thanks a lot! I'll try that!
