### ISSUE TITLE
Error EIO with nodejs

### ISSUE THREAD

**Issue by yovanoc** [primus/primus#724]
**Version:** Last

**Environment:**
  - **Operating system:** Linux & MacOS
  - **Browser:** Nope
  - **Node.js:** 12.3.1

**Expected result:** No error

**Actual result:**

<img width="511" alt="Capture d’écran 2019-05-28 à 14 20 51" src="https://user-images.githubusercontent.com/7302317/58477499-f5f12100-8153-11e9-8ac2-a168df0ae7d0.png">

I think it's one of the latest commit for engine.io-client browser support who breaks that in nodejs but not sure

**Comment by lpinca** [comment]
I can't reproduce

```js
'use strict';

const Primus = require('primus');
const http = require('http');

const server = http.createServer();
const primus = new Primus(server, { transformer: 'engine.io' });

primus.on('connection', function(spark) {
  spark.on('data', spark.write);
});

server.listen(function() {
  const { port } = this.address();
  const socket = new primus.Socket(`http://localhost:${port}`);

  socket.on('open', function() {
    socket.write('Hello');
  });

  socket.on('data', function(data) {
    console.log(data);
  });
});
```

**Comment by yovanoc** [comment]
Before this code was working great to directly require the client part in nodejs, now it isn't.

```js
const EventEmitter = require('events');
const Primus = require('primus');

const primus = new Primus(new EventEmitter(), {
  transformer: 'engine.io'
});

primus.save(__dirname + '/primus-eio.js', (err) => {
  console.log("primus-eio saved", err);
});
```

and 

```js
const Primus = require("./primus-eio");
```

**Comment by lpinca** [comment]
Are you able to specify on what version of primus and engine.io that worked? Also why using a browser build when there is a client specifically designed for Node.js?

**Comment by yovanoc** [comment]
Because I want a single final .js build file and it doesn't work with webpack otherwise, I will look for these versions soon

**Comment by lpinca** [comment]
Ping @yovanoc

**Comment by yovanoc** [comment]
Primus 7.2.3
Engine.IO 3.2.1

**Comment by lpinca** [comment]
It throw the same error.

```
$ cat index.js 
const EventEmitter = require('events');
const Primus = require('primus');

const primus = new Primus(new EventEmitter(), {
  transformer: 'engine.io',
  pingInterval: false
});

primus.save(__dirname + '/primus-eio.js', (err) => {
  console.log('primus-eio saved', err);
});
```

```
$ cat test.js 
const Primus = require('./primus-eio');
```

```
$ npm ls --depth 0
/Users/luigi/724
+-- engine.io@3.2.1
+-- engine.io-client@3.2.1
`-- primus@7.2.3
```

```
$ node test.js  
/Users/luigi/Desktop/724/primus-eio.js:3639
(function(f){var g;if(typeof window!=='undefined'){g=window}else if(typeof self!=='undefined'){g=self}g.eio=f()})(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(_dereq_,module,exports){
                                                                                                           ^

TypeError: Cannot set property 'eio' of undefined
    at /Users/luigi/Desktop/724/primus-eio.js:3639:108
    at Array.<anonymous> (/Users/luigi/Desktop/724/primus-eio.js:3639:114)
    at UMDish (/Users/luigi/Desktop/724/primus-eio.js:4:15)
    at Object.<anonymous> (/Users/luigi/Desktop/724/primus-eio.js:11:3)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

I don't think this is a regression.

**Comment by yovanoc** [comment]
I should have wrong in these versions but i'm sure, I will look carefully later tonight

**Comment by lpinca** [comment]
Closing due to inactivity.
