### ISSUE TITLE
Error: Cannot find module 'eventemitter3' on Windows

### ISSUE THREAD

**Issue by averri** [primus/primus#725]
**Version:** Primus 7.3.3

**Environment:**
  - **Operating system:** Windows 10, 64 bits
  - **Browser:** Chrome 74
  - **Node.js:** 10.15.3

**Expected result:**
The echo example should work as expected.

**Actual result:**
It cannot start the app contained in `index.js`.

```
$ node index.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'eventemitter3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\temp\primus\index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Steps to reproduce:**
Run the **echo** demo.

**Comment by 3rd-Eden** [comment]
Have you tried re-installing your node_modules?

If you did, and it didn't solve the problem, what is the output of `npm ls` (which will output the dependency tree to the CLI)

**Comment by 3rd-Eden** [comment]
Actually, I think didn't install the `node_modules` in the root of the `primus` repo that you cloned.  Make sure you install those dependencies before running any of the examples in our `example` folder.

**Comment by averri** [comment]
@3rd-Eden, re-installing the modules fixed the reported the issue. The server is rendering the `index.html` correctly, but the resource `http://localhost:8080/primus/primus.js` is not found. :

![image](https://user-images.githubusercontent.com/1898447/58543834-1c689800-81f8-11e9-9359-908ee6fd6253.png)

**Comment by averri** [comment]
The dependencies:

```
        /c/temp/primus/examples/echo (master)
        $ npm ls
        echo@0.0.0 C:\temp\primus\examples\echo
        +-- eventemitter3@3.1.2
        `-- primus@7.3.3
          +-- access-control@1.0.1
          | +-- millisecond@0.1.2
          | +-- setheader@1.0.1 deduped
          | `-- vary@1.1.2
          +-- asyncemit@3.0.1
          +-- create-server@1.0.2
          | `-- connected@0.0.2
          +-- diagnostics@2.0.1
          | +-- colorspace@1.1.2
          | | +-- color@3.0.0
          | | | +-- color-convert@1.9.3
          | | | | `-- color-name@1.1.3
          | | | `-- color-string@1.5.3
          | | |   +-- color-name@1.1.3 deduped
          | | |   `-- simple-swizzle@0.2.2
          | | |     `-- is-arrayish@0.3.2
          | | `-- text-hex@1.0.0
          | +-- enabled@2.0.0
          | +-- kuler@1.0.1
          | | `-- colornames@1.1.1
          | `-- storage-engine@3.0.4
          |   +-- enabled@2.0.0
          |   `-- eventemitter3@3.1.2 deduped
          +-- eventemitter3@3.1.2 deduped
          +-- forwarded-for@1.0.1
          +-- fusing@1.0.0
          | +-- emits@3.0.0
          | `-- predefine@0.1.2
          |   `-- extendible@0.1.1
          +-- nanoid@2.0.3
          +-- setheader@1.0.1
          | `-- diagnostics@1.1.1
          |   +-- colorspace@1.1.2 deduped
          |   +-- enabled@1.0.2
          |   | `-- env-variable@0.0.5
          |   `-- kuler@1.0.1 deduped
          `-- ultron@1.1.1

```

**Comment by lpinca** [comment]
@averri the build script is partially broken on windows but the following commands should work:

```
git clone https://github.com/primus/primus.git
cd primus
npm i --no-package-lock
mkdir dist
npx browserify primus.js -s Primus -p deumdify > dist/primus.js
cd examples\echo
npm i --no-package-lock
node index.js
```

Feel free to file a PR to fix the [build script](https://github.com/primus/primus/blob/d3c41d29ab24a0441665c95404f6f783dac407e6/package.json#L7) to make it work on Windows.
