### ISSUE TITLE
 PrimusError: Missing dependencies for transformer: "engine.io"

### ISSUE THREAD

**Issue by sido420** [primus/primus#726]
**Version:**
7.3.3

**Environment:**
  - **Operating system:** Linux
  - **Browser:** n/a
  - **Node.js:** v10.16.0

**Expected result:**
The program should just work normally.

**Actual result:**
It crashes with the following message:
```
Primus: Missing required npm dependency for engine.io 
Primus: Please run the following command and try again:                                                      
Primus:                                               
Primus:   npm install --save engine.io                
Primus:                                               
error: In app.js: Uncaught exception thrown with errorr:   PrimusError: Missing dependencies for transformer: "engine.io" 
```

**Steps to reproduce:**
Not sure how to reproduce yet but I have the following dir structure.

In `/srv` dir, I have the `node_modules` dir with all dependencies installed and seems to work fine for other modules.
```
root@de442b49583b:/srv# ls -lah node_modules/ | egrep -i "primus|engine"                                       
drwxr-xr-x 1 root root 4.0K Jun  6 02:29 engine.io     
drwxr-xr-x 1 root root 4.0K Jun  6 02:29 engine.io-client                                                      
drwxr-xr-x 1 root root 4.0K Jun  6 02:29 engine.io-parser                                                      
drwxr-xr-x 1 root root 4.0K Jun  6 02:48 primus
drwxr-xr-x 1 root root 4.0K Jun  6 02:29 primus-emit   
drwxr-xr-x 1 root root 4.0K Jun  6 02:29 primus-emitter  
```
The actual node.js code resides inside `/srv/src` dir though. node.js seems to pick up all modules just fine except primus.

```
root@de442b49583b:/srv#  egrep -i "primus|engine" package.json 
        "engine.io": "^3.2.1",
        "engine.io-client": "^3.3.2",
        "primus": "7.3.3",
        "primus-emit": "^1.0.0",
        "primus-emitter": "^3.1.1",
```

I start my program using:
```
cd /srv/src && nodemon server.js
```

**Comment by sido420** [comment]
Primus config object:
```
 {
..       
        pathname: '/primus', // The URL namespace that Primus can own
        parser: 'JSON',
        compression: true,
        transformer: 'engine.io',  
        transport: { wsEngine: 'uws' },


        namespace: 'mp', 
        interval: 5000, 
        address: add,
        redis: Redis,
        latency: 2000,
        concurrently: 100, 
        url: '/primus/...',


    };
```

**Comment by sido420** [comment]
I actually tried installing modules inside `src/` dir and also tried creating a shortcut to `node_modules/` in `/srv`

`/srv/src/node_modules` --> `/srv/node_modules`

**Comment by sido420** [comment]
Also tried in the container.
```
npm install -g engine.io  
```

**Comment by lpinca** [comment]
I can't reproduce:

```
.
|-- node_modules
`-- src
    `-- server.js
```

```js
'use strict';

const Primus = require('primus');
const http = require('http');

const server = http.createServer();
const primus = new Primus(server);

primus.on('connection', (spark) => {
  console.log(spark.id, 'connected');
});

server.listen(() => {
  const { port } = server.address();
  const socket = new primus.Socket(`http://localhost:${port}`);
});
```

**Comment by sido420** [comment]
You did not use the same configuration. 

If what I used is the default, any ideas how I should go about debugging it?

I'm running the setup inside a container and tried all kinds of installation options but keep getting the same error.

**Comment by lpinca** [comment]
I don't know, there is only a normal require on the server https://github.com/primus/primus/blob/d3c41d29ab24a0441665c95404f6f783dac407e6/transformers/engine.io/server.js#L3.

I'd start from my the example above and keep adding stuff until it breaks to isolate the issue.

**Comment by sido420** [comment]
Please try making the following change to your code:
```
const primus_options = {                                        
    pathname: '/primus',                                                                
    parser: 'JSON',                                             
    compression: true,                                          
    transformer: 'engine.io',                                                   
    transport: { wsEngine: 'uws' }                              
};                                                              

const primus = new Primus(server, primus_options); 
```

that throws the same error.

**Comment by sido420** [comment]
here are complete details:
```
 Primus:                        
 Primus: Missing required npm dependency for engine.io          
 Primus: Please run the following command and try again:        
 Primus:                        
 Primus:   npm install --save engine.io                         
 Primus:                        
                                
 /srv/node_modules/primus/index.js:290                          
         throw new PrimusError(this.is(transformer, Primus.transformers).missing(), this);                                      
         ^                      
 PrimusError: Missing dependencies for transformer: "engine.io" 
     at Primus.initialise (/srv/node_modules/primus/index.js:290:15)                                                            
     at new Primus (/srv/node_modules/primus/index.js:111:8)    
     at Object.<anonymous> (/srv/src/primus.js:18:16)           
     at Module._compile (internal/modules/cjs/loader.js:776:30) 
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)                                                   
     at Module.load (internal/modules/cjs/loader.js:653:32)     
     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)   
     at Function.Module._load (internal/modules/cjs/loader.js:585:3)                                                            
     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)                                                         
     at startup (internal/bootstrap/node.js:283:19) 
```

**Comment by sido420** [comment]
here is complete code:
```
root@cf5e667ec168:/srv# cat /srv/src/primus.js         
'use strict';              
                           

console.log('In primus.js .. ');                       
const Primus = require('primus');                      
const http = require('http');                          

const server = http.createServer();                    

const primus_options = {   
    pathname: '/primus',                                              
    parser: 'JSON',        
    compression: true,     
    transformer: 'engine.io',                                  
    transport: { wsEngine: 'uws' }                     
};                         

const primus = new Primus(server, primus_options);     

primus.on('connection', (spark) => {                   
  console.log(spark.id, 'connected');                  
});                        

server.listen(() => {      
  const { port } = server.address();                   
  const socket = new primus.Socket(`http://localhost:${port}`);                                               
  console.log(`Listening on ${port}`);                 
});  
```

**Comment by sido420** [comment]
If I remove the 2 lines from config then it works.
```
    transformer: 'engine.io',                                  
    transport: { wsEngine: 'uws' } 
```

**Comment by sido420** [comment]
The problem is 
```
    transport: { wsEngine: 'uws' }                              
```
If I remove it then engine.io works fine. 

How do I make this work and what broke the transport option? I remember using it on your suggestion in one of the previous issues and it used to work fine. 
See https://github.com/primus/primus/issues/499

**Comment by sido420** [comment]
Also, the error/exception is misleading.

**Comment by lpinca** [comment]
Did you install uws? Since Engine.IO was told to use uws I guess it tried to require it.
I agree that the error is misleading. Feel free to file a PR to fix it.

**Comment by lpinca** [comment]
Closing due to inactivity.
