### ISSUE TITLE
__name is not defined

### ISSUE THREAD

**Issue by ccorcos** [primus/primus#781]
**Version:** 8.0.7

**Environment:**
  - **Operating system:** MacOS
  - **Browser:** Chrome
  - **Node.js:** 19.4.0

I'm just getting started and running into this issue in the browser:

```
Uncaught ReferenceError: __name is not defined
    at g.client (primuslib.js:3662:80)
    at g.initialise (primuslib.js:3057:10)
    at new g (primuslib.js:2705:10)
    at new Cd (Subscriber.ts:11:17)
    at index.tsx:24:20
    at index.tsx:52:30
```

On the server, I'm generating the client library:

```
const app = express()
const server = http.createServer(app)
const primus = new Primus(server)
fs.writeFileSync(path("src/client/primuslib.js"), this.primus.library())
```

And then on the client:

```
const Primus = require("./primuslib")
const primus = new Primus("http://localhost:8080")
```

And I get that ReferenceError... I'm not sure what's going on. I looked at the code and there's definitely a __name variable that is not defined. Any thoughts? Am I missing something?

**Comment by davidsoderberg** [comment]
I also get this with 8.0.9 and node 18.16.0.
